services:
  book-wise: 
    container_name: book-wise
    image: bitnami/postgresql
    ports:
     - 5432:5432
    environment:
      POSTGRESQL_USERNAME: ${DATABASE_USERNAME}
      POSTGRESQL_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRESQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - book_wise_data:/bitnami/postgresql

volumes:
  book_wise_data: